# Generated by Django 2.0.1 on 2018-02-07 10:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=40)),
                ('created', models.CharField(max_length=30)),
                ('updated', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('start_dateTime', models.CharField(max_length=50)),
                ('end_dateTime', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('event_dump', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceEmail', models.CharField(max_length=100)),
                ('resourceId', models.CharField(max_length=500)),
                ('generatedResourceName', models.CharField(max_length=100)),
                ('resourceType', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('resourceCategory', models.CharField(max_length=20)),
                ('buildingId', models.CharField(blank=True, max_length=10)),
                ('floorName', models.IntegerField(blank=True)),
                ('resourceDumpdata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('events', models.ManyToManyField(blank=True, to='MyResources.Events')),
            ],
        ),
    ]
