# Generated by Django 2.0.1 on 2018-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0002_resources_resourceuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='buildingId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resourceType',
            field=models.CharField(max_length=20),
        ),
    ]
