# Generated by Django 2.0.1 on 2018-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0003_auto_20180209_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_dateTime',
            field=models.DateTimeField(),
        ),
    ]
