# Generated by Django 2.0.1 on 2018-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0004_auto_20180209_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_dateTime',
            field=models.DateTimeField(),
        ),
    ]
