# Generated by Django 2.0.1 on 2018-02-10 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0005_auto_20180209_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resourceCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
