# Generated by Django 2.0.1 on 2018-02-10 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0006_resources_resourcecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resourceCreated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
