# Generated by Django 2.0.1 on 2018-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0008_events_resources_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='roomName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resources',
            name='roomPassword',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
