# Generated by Django 2.0.1 on 2018-02-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0010_resources_synctoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='roomLoginName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resources',
            name='roomUrl',
            field=models.URLField(blank=True),
        ),
    ]
