# Generated by Django 2.0.1 on 2018-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0011_auto_20180223_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
