# Generated by Django 2.0.1 on 2018-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0012_events_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
