# Generated by Django 2.0.1 on 2018-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0013_auto_20180226_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resourceName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
