# Generated by Django 2.0.1 on 2018-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0014_resources_resourcename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='floorName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
