# Generated by Django 2.0.1 on 2018-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0016_auto_20180226_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resourceEmail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
