# Generated by Django 2.0.1 on 2018-02-28 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0018_auto_20180228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='recurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], size=None),
        ),
    ]
