# Generated by Django 2.0.1 on 2018-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0019_auto_20180228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
