# Generated by Django 2.0.1 on 2018-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0020_auto_20180301_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
