# Generated by Django 2.0.1 on 2018-03-05 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0022_events_recurr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='recurrence',
        ),
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
