# Generated by Django 2.0.1 on 2018-03-05 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0023_auto_20180305_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='resources_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=[], size=None),
        ),
    ]
