# Generated by Django 2.0.1 on 2018-03-06 08:49

from django.db import migrations, models
from django.utils import timezone


def edit_null_items(apps, schema_editor):
    Events = apps.get_model("MyResources", "Events")
    for event in Events.objects.all():
        if event.created ==None:
            event.created=timezone.now().replace(year=1900)
            event.save()
        if event.updated ==None:
            event.updated=timezone.now().replace(year=1901)
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0024_auto_20180305_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, edit_null_items)
    ]
