# Generated by Django 2.0.1 on 2018-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0025_auto_20180306_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
