# Generated by Django 2.0.1 on 2018-03-06 09:06

from django.db import migrations, models


def edit_null_items(apps, schema_editor):
    Events = apps.get_model("MyResources", "Events")
    for event in Events.objects.all():
        if event.creator ==None:
            event.creator=''
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0025_auto_20180306_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, edit_null_items)
    ]
