# Generated by Django 2.0.1 on 2018-03-22 12:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0026_auto_20180306_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='changed_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='events',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyResources.Events', to_field='event_id'),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.TextField(null=True),
        ),

    ]
