# Generated by Django 2.0.1 on 2019-10-22 08:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyResources', '0027_auto_20180322_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
